# Generated by Django 4.1 on 2023-05-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_nft_object_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft_object",
            name="token_URI",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nft_object",
            name="tx_hash",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
