# Generated by Django 4.2.1 on 2023-05-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_category_nft_object_delete_nft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('WithHuman', 'WithHuman')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nft_object',
            name='description',
            field=models.TextField(default='no'),
        ),
    ]
