# Generated by Django 4.2.1 on 2023-05-25 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_nftuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftuser',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='nftuser',
            name='user_image',
            field=models.ImageField(default='default_image.jpg', null=True, upload_to='images/user_images/%Y/%m/%d/'),
        ),
    ]
