# Generated by Django 4.2.1 on 2023-05-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_nftuser_birth_date_alter_nftuser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
