# Generated by Django 4.2.1 on 2023-05-25 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_nftuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftuser',
            name='nation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.nation'),
        ),
    ]
