# Generated by Django 4.2.1 on 2023-05-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_nftuser_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
