# Generated by Django 4.1 on 2023-05-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_nftuser_password1_nftuser_password2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nftuser",
            name="wallet_addr",
        ),
        migrations.AddField(
            model_name="nftuser",
            name="NFT_private_key",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="nftuser",
            name="NFT_public_key",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="nftuser",
            name="NFT_wallet_addr",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
